Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -13,6 +13,7 @@ variables:
 steps:
 - checkout: self
 
+# Instalação de Certificados e Perfil de Provisionamento
 - task: InstallAppleCertificate@2
   inputs:
     certSecureFile: 'CertificatesDistribution.p12'
@@ -25,6 +26,7 @@ steps:
     provProfileSecureFile: 'DistributionWhiteLabel.mobileprovision'
   displayName: 'Install Apple Provisioning Profile'
 
+# Preparação do ambiente
 - script: |
     cd $(Build.SourcesDirectory)
     pod update
@@ -36,6 +38,7 @@ steps:
     xcodebuild clean
   displayName: 'Clean Xcode data'
 
+# Verificações
 - script: |
     if [ ! -f $(Build.SourcesDirectory)/ExportOptions.plist ]; then
       echo "Error: ExportOptions.plist not found!"
@@ -43,19 +46,7 @@ steps:
     fi
   displayName: 'Check ExportOptions.plist exists'
 
-- script: |        
-    # # Ensure Archive directory exists and create it if necessary
-    # mkdir -p $(Build.SourcesDirectory)/build/
-    
-    # # Set permissions for Archive directory to ensure it's writable
-    # chmod 755 $(Build.SourcesDirectory)/build/
-    
-    # # Check if Archive directory is writable 
-    # if [ ! -d "$(Build.SourcesDirectory)/build/" ]; then
-    #     echo "Error: Archive directory not found or not writable!"
-    #     exit 1
-    # fi
-
+- script: |
     # Ensure Export directory exists and create it if necessary
     mkdir -p $(Build.ArtifactStagingDirectory)/
     
@@ -67,56 +58,42 @@ steps:
         echo "Error: Export directory not found or not writable!"
         exit 1
     fi
+  displayName: 'Prepare Export Directory'
 
-    for target in WhiteLabel 
+# Atualização do Info.plist
+- script: |
+    infoPlistPath="$(Build.SourcesDirectory)/$(scheme)/Info.plist"
+    chmod 644 $infoPlistPath
+    /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $(BUNDLE_ID)" $infoPlistPath
+
+    current_version=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" $infoPlistPath)
+    new_version=$((APP_VERSION + 1))
+    /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $new_version" $infoPlistPath
+  displayName: 'Update Info.plist'
+
+# Arquivo e Exportação
+- script: |      
+    xcodebuild archive -workspace $(xcWorkspacePath) -scheme $(scheme) \
+    -archivePath $(Build.SourcesDirectory)/build/$(scheme).xcarchive
+    
+    xcodebuild -exportArchive -archivePath $(Build.SourcesDirectory)/build/$(scheme).xcarchive \
+    -exportOptionsPlist $(Build.SourcesDirectory)/ExportOptions.plist \
+    -exportPath $(Build.ArtifactStagingDirectory)/
+  displayName: 'Archive and Export IPA'
+
+# Upload
+- script: |
+    retry_count=0
+    max_retries=3
+    while [ $retry_count -lt $max_retries ]
     do
-      echo "Processing target: $target"
-      
-      infoPlistPath="$(Build.SourcesDirectory)/$target/Info.plist"
-      echo "---- Info.plist BEFORE any updates ----"
-      cat $infoPlistPath
-
-      chmod 644 $infoPlistPath
-      /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $(BUNDLE_ID)" $infoPlistPath
-
-      current_version=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" $infoPlistPath)
-      new_version=$((APP_VERSION + 1))
-      /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $new_version" $infoPlistPath
-      
-      echo "Archiving $target..."
-      xcodebuild archive -workspace $(xcWorkspacePath) -scheme $target \
-      -archivePath $(Build.SourcesDirectory)/build/$target.xcarchive
-      
-      echo "Exporting IPA for $target..."
-      rm -rf $(Build.ArtifactStagingDirectory)/$IPA_NAME-$target.ipa
-      xcodebuild -exportArchive -archivePath $(Build.SourcesDirectory)/build/$target.xcarchive \
-      -exportOptionsPlist $(Build.SourcesDirectory)/ExportOptions.plist \
-      -exportPath $(Build.ArtifactStagingDirectory)/
-      
-      echo "---- Info.plist AFTER updates ----"
-      cat $infoPlistPath
-      
-      if [ ! -f $(Build.ArtifactStagingDirectory)/$IPA_NAME-$target.ipa ]; then
-          echo "Error: IPA not found for target $target!"
-          exit 1
-      fi
-      
-      mkdir tempIPA_$target
-      unzip $(Build.ArtifactStagingDirectory)/$IPA_NAME-$target.ipa -d tempIPA_$target/
-      /usr/libexec/PlistBuddy -c "Print CFBundleVersion" tempIPA_$target/Payload/$target.app/Info.plist
-      
-      retry_count=0
-      max_retries=3
-      while [ $retry_count -lt $max_retries ]
-      do
-        xcrun altool --upload-app --type ios --file $(Build.ArtifactStagingDirectory)/$IPA_NAME-$target.ipa --username $(APPLE_DEVELOPER_USERNAME) --password $(APPLE_DEVELOPER_PASSWORD) && break
-        retry_count=$((retry_count+1))
-        echo "Retry $retry_count/$max_retries..."
-        sleep 10
-      done
-      if [ $retry_count -eq $max_retries ]; then
-        echo "Failed to upload after $max_retries attempts. Exiting..."
-        exit 1
-      fi
+      xcrun altool --upload-app --type ios --file $(Build.ArtifactStagingDirectory)/$IPA_NAME-$(scheme).ipa --username $(APPLE_DEVELOPER_USERNAME) --password $(APPLE_DEVELOPER_PASSWORD) && break
+      retry_count=$((retry_count+1))
+      echo "Retry $retry_count/$max_retries..."
+      sleep 10
     done
-  displayName: 'Process and Upload Targets'
+    if [ $retry_count -eq $max_retries ]; then
+      echo "Failed to upload after $max_retries attempts. Exiting..."
+      exit 1
+    fi
+  displayName: 'Upload to App Store'
