Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -135,38 +135,38 @@ steps:
     -archivePath $(Build.SourcesDirectory)/build/WhiteLabel.xcarchive
   displayName: 'Archive Project'
 
-# Archive and export .ipa
-- script: |
-    # Set the IPA name with a timestamp
-    TIMESTAMP=$(date +"%Y%m%d%H%M%S")
-    IPA_DIRECTORY="WhiteLabel_$TIMESTAMP"
-    IPA_NAME="WhiteLabel.ipa"  # The actual IPA will have this generic name
+# # Archive and export .ipa
+# - script: |
+#     # Set the IPA name with a timestamp
+#     TIMESTAMP=$(date +"%Y%m%d%H%M%S")
+#     IPA_DIRECTORY="WhiteLabel_$TIMESTAMP"
+#     IPA_NAME="WhiteLabel.ipa"  # The actual IPA will have this generic name
     
-    # Remove any old IPAs and directories
-    rm -rf $(Build.ArtifactStagingDirectory)/*.ipa
-    rm -rf $(Build.ArtifactStagingDirectory)/$IPA_DIRECTORY
+#     # Remove any old IPAs and directories
+#     rm -rf $(Build.ArtifactStagingDirectory)/*.ipa
+#     rm -rf $(Build.ArtifactStagingDirectory)/$IPA_DIRECTORY
     
-    # Archive and export
-    xcodebuild -exportArchive -archivePath $(Build.SourcesDirectory)/build/WhiteLabel.xcarchive \
-    -exportOptionsPlist $(Build.SourcesDirectory)/ExportOptions.plist \
-    -exportPath $(Build.ArtifactStagingDirectory)/$IPA_DIRECTORY
+#     # Archive and export
+#     xcodebuild -exportArchive -archivePath $(Build.SourcesDirectory)/build/WhiteLabel.xcarchive \
+#     -exportOptionsPlist $(Build.SourcesDirectory)/ExportOptions.plist \
+#     -exportPath $(Build.ArtifactStagingDirectory)/$IPA_DIRECTORY
     
-    # Confirm that the IPA was exported correctly
-    if [ ! -f $(Build.ArtifactStagingDirectory)/$IPA_DIRECTORY/$IPA_NAME ]; then
-        echo "Error: IPA not found!"
-        exit 1
-    fi
+#     # Confirm that the IPA was exported correctly
+#     if [ ! -f $(Build.ArtifactStagingDirectory)/$IPA_DIRECTORY/$IPA_NAME ]; then
+#         echo "Error: IPA not found!"
+#         exit 1
+#     fi
     
-    # List contents of the directory
-    unzip $(Build.ArtifactStagingDirectory)/$IPA_DIRECTORY/$IPA_NAME -d extractedIPA
-    ls -al extractedIPA
-    echo "Contents of the export directory:"
-    ls -al $(Build.ArtifactStagingDirectory)/$IPA_DIRECTORY
+#     # List contents of the directory
+#     unzip $(Build.ArtifactStagingDirectory)/$IPA_DIRECTORY/$IPA_NAME -d extractedIPA
+#     ls -al extractedIPA
+#     echo "Contents of the export directory:"
+#     ls -al $(Build.ArtifactStagingDirectory)/$IPA_DIRECTORY
     
-    # Check details of the IPA
-    stat $(Build.ArtifactStagingDirectory)/$IPA_DIRECTORY/$IPA_NAME
-  displayName: 'Archive, Export .ipa and Check Details'
+#     # Check details of the IPA
+#     stat $(Build.ArtifactStagingDirectory)/$IPA_DIRECTORY/$IPA_NAME
+#   displayName: 'Archive, Export .ipa and Check Details'
 
-- script: |
-    xcrun altool --upload-app --type ios --file $(Build.ArtifactStagingDirectory)/$IPA_DIRECTORY/$IPA_NAME --username $(APPLE_DEVELOPER_USERNAME) --password $(APPLE_DEVELOPER_PASSWORD)
-  displayName: 'Upload to App Store'
+# - script: |
+#     xcrun altool --upload-app --type ios --file $(Build.ArtifactStagingDirectory)/$IPA_DIRECTORY/$IPA_NAME --username $(APPLE_DEVELOPER_USERNAME) --password $(APPLE_DEVELOPER_PASSWORD)
+#   displayName: 'Upload to App Store'
