Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -67,10 +67,33 @@ steps:
 - script: cat $(infoPlistPath)
   displayName: 'Debug: Display Info.plist Before Update'
 
-# Increment Version Before Upload
+# Check and Modify Permissions
+- script: ls -l $(infoPlistPath)
+  displayName: 'Check Info.plist permissions'
+  
+- script: chmod 644 $(infoPlistPath)
+  displayName: 'Change Info.plist permissions'
+
+# Check and Unlock File
+- script: chflags -v $(infoPlistPath)
+  displayName: 'Check if Info.plist is locked'
+  
+- script: chflags nouchg $(infoPlistPath)
+  displayName: 'Unlock Info.plist'
+
+# Increment Version
 - script: |
-    /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $(Build.BuildId)" $(infoPlistPath)
-  displayName: 'Increment CFBundleVersion using Build ID'
+    current_version=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" $(infoPlistPath))
+    if [ -z "$current_version" ]; then
+      echo "CFBundleVersion not found. Exiting."
+      exit 1
+    else
+      echo "Current Version: $current_version"
+      new_version=$((current_version + 1))
+      echo "New Version: $new_version"
+      /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $new_version" $(infoPlistPath)
+    fi
+  displayName: 'Increment CFBundleVersion by 1'
 
 # Debug: Display Info.plist After Update
 - script: cat $(infoPlistPath)
@@ -113,33 +136,6 @@ steps:
     -exportOptionsPlist $(Build.SourcesDirectory)/ExportOptions.plist \
     -exportPath $(Build.ArtifactStagingDirectory)
   displayName: 'Archive and export .ipa'
-
-# Debugging Steps (Init)
-- script: |
-    unzip -q $(Build.ArtifactStagingDirectory)/WhiteLabel.ipa -d $(Pipeline.Workspace)/a/WhiteLabel
-    if [ -f "$(Pipeline.Workspace)/a/WhiteLabel/Payload/WhiteLabel.app/Info.plist" ]; then
-      echo "Info.plist file found."
-    else
-      echo "Info.plist file not found. Exiting."
-      exit 1
-    fi
-  displayName: 'Validate Info.plist in IPA'
-
-- script: |
-    unzip -q $(Build.ArtifactStagingDirectory)/WhiteLabel.ipa -d $(Pipeline.Workspace)/a/WhiteLabel
-    plist=$(Pipeline.Workspace)/a/WhiteLabel/Payload/WhiteLabel.app/Info.plist
-    if [ -f "$plist" ]; then
-      echo "Info.plist file found."
-      /usr/libexec/PlistBuddy -c "Print CFBundleVersion" "$plist"
-    else
-      echo "Info.plist file not found. Exiting."
-      exit 1
-    fi
-  displayName: 'Validate CFBundleVersion in IPA'
-
-- script: cat $(Pipeline.Workspace)/a/WhiteLabel/Payload/WhiteLabel.app/Info.plist
-  displayName: 'Display Info.plist for debugging'
-# Debugging Steps (End)
 
 - script: |
     xcrun altool --upload-app -f "$(Build.ArtifactStagingDirectory)/WhiteLabel.ipa" \
