Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -130,6 +130,18 @@ steps:
     fi
   displayName: 'Validate Info.plist in IPA'
 
+- script: |
+    unzip -q $(Build.ArtifactStagingDirectory)/WhiteLabel.ipa -d $(Pipeline.Workspace)/a/WhiteLabel
+    plist=$(Pipeline.Workspace)/a/WhiteLabel/Payload/WhiteLabel.app/Info.plist
+    if [ -f "$plist" ]; then
+      echo "Info.plist file found."
+      /usr/libexec/PlistBuddy -c "Print CFBundleVersion" "$plist"
+    else
+      echo "Info.plist file not found. Exiting."
+      exit 1
+    fi
+  displayName: 'Validate CFBundleVersion in IPA'
+
 - script: cat $(Pipeline.Workspace)/a/WhiteLabel/Payload/WhiteLabel.app/Info.plist
   displayName: 'Display Info.plist for debugging'
 # Debugging Steps (End)
